# Generated by Django 3.0.5 on 2020-04-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_init', models.DateTimeField(db_index=True, verbose_name='Beggining date')),
                ('status', models.CharField(choices=[('n', 'New'), ('p', 'Processing'), ('d', 'Done')], default='n', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Main Task',
                'verbose_name_plural': 'Main Tasks',
                'ordering': ['-date_init'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='tag')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Resolution')),
                ('status', models.CharField(choices=[('n', 'New'), ('p', 'Processing'), ('d', 'Done')], default='n', max_length=1, verbose_name='Status')),
                ('date_init', models.DateTimeField(db_index=True, verbose_name='Beggining date')),
                ('maintask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workpoint.MainTask', verbose_name='MainTasks')),
            ],
            options={
                'verbose_name': 'Point',
                'verbose_name_plural': 'Points',
            },
        ),
    ]
